### ISSUE TITLE
Is it possible to parse bytes to JSON?

### ISSUE THREAD

**Issue by TheOnlyArtz** [JuliaWeb/WebSockets.jl#117]
I got the next code:
```julia
import OpenTrick
import WebSockets

io = OpenTrick.opentrick(WebSockets.open, "wss://gateway.discord.gg/?v=6&encoding=json")

### How would I parse the bytes to JSON?

**Comment by hustf** [comment]
It is possible, if I understand correctly. You need of couse whole strings
to do it.
 Is your application really speed sensitive, or are you ok with waiting for
a few microseconds every message?

Den tor. 27. sep. 2018, 17:12 skrev Amit Katz <notifications@github.com>:

**Comment by TheOnlyArtz** [comment]
@hustf 
Hey, thank you for the quick response I've managed to fix it and parse bytes to JSON, but I got another question, I'm trying to keep receiving data from the gateway and I'm trying to do
```julia
while isopen(connection)
    println(WebSockets.read(connection))
end
```
 for some reason it never prints and the connection is open (checked by doing `println("aaa")` inside it.

**Comment by hustf** [comment]
The information is a little thin here. It's a connection, so both sides
depend on what the other side is doing. If both sides read simultaneously,
you are stuck for ever. So this can be hard to get right, and for many
applications you need some sort of parallelism and a buffer.
I would recommend using readguarded instead of reading, though.

Den tor. 27. sep. 2018, 19:58 skrev Amit Katz <notifications@github.com>:
