### ISSUE TITLE
Restrictive HTTP.jl version limits are causing downstream problems

### ISSUE THREAD

**Issue by rdeits** [JuliaWeb/WebSockets.jl#119]
I've noticed a bunch of weird bugs in various web packages (for example: https://github.com/JunoLab/Blink.jl/issues/154 ), and I think I finally understand what's going on. The issue begins with the fact that WebSockets v1.0.0 declares a requirement on HTTP.jl but with no specified version range: https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/WebSockets/versions/1.0.0/requires . That's not much of a problem on it's own, but WebSockets v1.0.1 *does* provide an upper bound on its HTTP.jl version: https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/WebSockets/versions/1.0.1/requires and WebSockets v1.0.2 and v1.0.3 make that upper bound even more restrictive. 

This is a problem because, in order to provide compatible versions of WebSockets and HTTP.jl, the package resolver can do one of two things:

1. Provide WebSockets.jl v1.0.3 (the latest), which restricts HTTP.jl to v0.6.14
2. Provide HTTP.jl v0.7.1 (the latest) and WebSockets.jl v1.0.0 (since WebSockets v1.0.0 has no upper bound on its HTTP.jl requirement)

The resolver happens to pick option 2, but that configuration is *actually* broken. Unfortunately, the package manager doesn't know it's broken because WebSockets v1.0.0 has no restrictions on its HTTP.jl version compatibility. 

The result is general brokenness in the tools like WebIO that try to use WebSockets.jl and HTTP.jl together. The problem is "fixed" by pinning WebSockets.jl to version 1.0.1, 1.0.2, or 1.0.3, which essentially forces the package manager to choose option 1 (e.g. https://github.com/JunoLab/Blink.jl/issues/154#issuecomment-423782432 ).

As far as I know, there are two ways to solve this: 

1. Make a PR to METADATA.jl adding lower and upper bounds to the HTTP.jl requirement in all the older versions of WebSockets.jl. It's unusual for the REQUIRE file in METADATA.jl to differ from the one in the package, but it is allowed precisely for cases like this. 
2. Fix the compatibility with HTTP.jl and release a new version of WebSockets.jl that supports HTTP.jl v0.7. That will create a new option for the package manger to install the latest HTTP.jl and WebSockets.jl, which it should happily do.

I think we actually need to do both: if we only do option 2, things will keep working...for a while. But we may get the same problem later on when HTTP.jl releases a new version that exceeds whatever upper bound WebSockets.jl v1.x.x specifies. 

By the way, this should all get better when we fully move to Pkg3 (and specifying compatibility exactly in Project.toml), but we're not quite there yet.

**Comment by hustf** [comment]
Thanks for the references and the heads up. We will make this less painful soon. The reason for the latest WebSocket versions are hopefully traceable through issues, release comments and prs. 

I may be wrong in my assumptions of how pkg3 is implemented now. However, in order to use capped versions, I believe referring packages may be better off referring few dependencies directly. E.g. import HTTP methods through WebSockets, and we may be able to keep a working stack even during revision sequences. This is of course not ideal, but if upper capping is to be useable it may be the best option. Issues like this lies of course behind the HTTP consolidation package. 

We can expect some more versions of HTTP, and it is difficult to detect all consequences through unit tests.

Unless we run into unexpected issues, there will be a pr for option 2, possibly already tomorrow. There is a branch for it already, but it is not at the last commit. 

Then, it is possible HTTP will release the next version before this.

I have a hunch Ido not fully understand how pkg3 works yet. Will we need to use .toml files in order to use it fully? Will come back to this.

**Comment by rdeits** [comment]
No worries. Just to be clear, there's absolutely no problem with upper bounds on HTTP in your REQUIRE, and you can keep doing that in the future. The problem comes from the fact that WebSockets v1.0.0 didn't have those upper bounds, so it is mistakingly claiming compatibility with newer HTTP releases. If we just add the appropriate upper bound in METADATA (that just requires a PR to METADATA), then the brokenness will be resolved and you can continue to restrict your HTTP compatibility as necessary.

**Comment by hustf** [comment]
Ah, I see! Thank you. Will fix.
As long as last digit revisions do not require downstream changes, more packages probably ought to specify a range of compatible requirements. Few do now.

**Comment by hustf** [comment]
Made a PR to METADATA.jl adding lower and upper bounds to the HTTP.jl requirement in all the older versions of WebSockets.jl. 

Did nothing to sha's. 

Also added upper bounds to Julia versions back to v0.5, which seems like a good practice for similar reasons.

**Comment by rdeits** [comment]
Perfect, thank you!
