### ISSUE TITLE
small cosmetic bug:

### ISSUE THREAD

**Issue by zahachtah** [JuliaWeb/WebSockets.jl#99]
in the chat example, in file chat.jl on line 32 change to:

write(v.client, (connections[id].name * ": " * content))

so it writes the right name to other clients

**Comment by hustf** [comment]
Thank you. I will not fix this on 0.6, mostly because git is difficult.

The following part of the example is also misleading:
```
julia> include("chat.jl")
INFO: Loading HttpServer methods...
Chat server listening on 8000...
Listening on 0.0.0.0:8000...
```
...at least on a windows machine. Pasting 127.0.0.1:8000 into the chrome browser will work, but 0.0.0.0:8000 will not. If you have suggestions on how to fix that (or similar issues), it's greatly appreciated!
